### ISSUE TITLE
[BUG] Conversations cant be deleted

### ISSUE THREAD

**Issue by Aarontheissueguy** [nanu-c/axolotl#343]
### Description
Multiple chats with people after restart of the and Inconsistencies with desktop client. 

### Steps to Reproduce

1. Delete Conversation on Axolotl. 
2. Receive Message of conversation partner
3. Restart App
4. You now recieve messages in the new chat but the old one is still present.

**Expected behavior:** 
Conversations are deletes permanantly.

**Actual behavior:** [What actually happens]
You now recieve messages in the new chat but the old one is still present.
#### Versions

0.9.5

#### Device
What device or OS are you using?
UbuntuTouch VollaPhone

**Comment by Flaburgan** [comment]
@Aarontheissueguy thank you for taking time to report that issue. We released a 0.9.6 version which should solve it, please update and confirm.

**Comment by Aarontheissueguy** [comment]
I updated but cant confirm. Still cant delete conversations permanantly. Is there a way to hard reset conversations?

**Comment by nanu-c** [comment]
You can either delete all conversations by deleting /home/phablet/.local/share/textsecure.nanuc/db/db.sql or open that file with a sqlite dbrowser and delete the conversations in the database or use a sqlite cli to edit that file with sql commands.
