### ISSUE TITLE
[BUG] Error communicating with Signal servers

### ISSUE THREAD

**Issue by Shadowbird2468** [nanu-c/axolotl#564]
### Description

"Error communicating with Signal servers", while trying to register my phonenumber.

### Steps to Reproduce

1. Clearing all data with UTTT and reinstalling the app.
2. Getting a pin code to register my number.
3. Adding the code into the pin field.
4. Checking that signal servers are up.
5. Unregistering and trying to register again.
6. Repeat the same all the way from step 1. ~10 times during past 2days.

**Expected behavior:** After adding the pin code, I should be able to register my phonenumber.

**Actual behavior:** I add the pin, then I wait for few minutes till I get "Error communicating with Signal servers"

#### Versions 
1.0.4

#### Device
Oneplus 5, Ubuntu Touch (stable)

#### Link to Debug Log
https://pastebin.com/kj7ppXnp

**Comment by Shadowbird2468** [comment]
The error message:
---
Error communicating with Signal servers
×
Axolotl encountered an error communicating with Signal servers. Please try again.

If you're seeing that error multiple times, check the status of Signal servers. If it's fine, then please tell us there is a problem by opening an issue.

If you think that something is wrong on your side, you can unregister and register again. Be careful, your encryption key will change and you will lose all your messages if you choose to do that.
---

**Comment by nuehm-arno** [comment]
Should be resolved with v1.0.5... Please confirm and close the issue.

**Comment by Shadowbird2468** [comment]
Yes, it seems to work now!

**Comment by stemy2** [comment]
Nope ! I juste installed the version 1.2.0 and the bug is still there.
